#!/bin/bash

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"
cd ~

save() {
	local file="$1"
	[ -e "$file" ] && mv -v "$file"{,_$(date +%Y%m%d-%H%M)}
}

saveAndLink() {
	local file="$1"
	save "$file"
	ln -svf "$SCRIPT_PATH/$file"
}

save .bashrc
ln -svf /etc/profile .bashrc

chmod a+r "$SCRIPT_PATH/.gitconfig"
chmod a+x "$SCRIPT_PATH"
chmod a+x "$SCRIPT_PATH/.."
saveAndLink .gitconfig
