#!/bin/bash

[ -w /etc/vim ] || {
	echo >&2 "/etc/vim not writable for user $USER"
	exit 1
}

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"

chmod -v a+r "$SCRIPT_PATH/vimrc.local"
chmod -v a+x "$SCRIPT_PATH"
chmod -v a+x "$SCRIPT_PATH/.."
chmod -v a+x "$SCRIPT_PATH/../.."

[ -f /etc/vim/vimrc.local ] && [ ! -h /etc/vim/vimrc.local ] && mv -v /etc/vim/vimrc.local{,_$(date +%Y%m%d-%H%M)}
ln -sfv "$SCRIPT_PATH/vimrc.local" /etc/vim/vimrc.local
