#!/bin/bash

SCRIPT_FILE_NAME='/etc/profile.d/BorX.sh'

[ -w /etc/profile.d ] || {
	echo >&2 '/etc/profile.d not writable'
	exit 1
}

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)"

cat <<EOF >"$SCRIPT_FILE_NAME"
#!/bin/bash
SCRIPT_PATH='$SCRIPT_PATH'
[ -d "\$SCRIPT_PATH" ] && [ -r "\$SCRIPT_PATH" ] && [ -x "\$SCRIPT_PATH" ] && {
	for i in "\$SCRIPT_PATH"/*.sh; do
		[ -r "\$i" ] && . "\$i"
	done
	unset i
} || echo >&2 "No access to \$SCRIPT_PATH"
EOF

chmod a+r "$SCRIPT_FILE_NAME"
chmod a+x  "$SCRIPT_PATH"
chmod a+x  "$SCRIPT_PATH/etc"
chmod a+rx "$SCRIPT_PATH/etc/profile.d"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/01_history.sh"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/02_term.sh"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/11_shellAlias.sh"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/12_functions.sh"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/21_editors.sh"
chmod a+r  "$SCRIPT_PATH/etc/profile.d/31_color.sh"
